services:
  mysql:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-solmessage_db}
      MYSQL_USER: ${MYSQL_USER:-solmessage}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-solmessage}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    # environment:
    #   PMA_HOST: mysql
    #   PMA_USER: root
    #   PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy

  api:
    image: ghcr.io/error404ai/txtalk/api:${TAG}
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: ghcr.io/error404ai/txtalk/frontend:${TAG}
    restart: unless-stopped
    env_file:
      - ./apps/frontend/.env
    ports:
      - "3001:5173"
    depends_on:
      api:
        condition: service_started

volumes:
  mysql_data:
